availabilitycode:
  'AB': false
  'AD': false
  'CS': false
  'EX': false
  'IP': true
  'MD': true
  'NP': true
  'NY': true
  'OF': false
  'OI': false
  'OP': false
  'OR': false
  'PP': false
  'RF': false
  'RM': false
  'RP': true
  'RU': true
  'TO': true
  'TP': true
  'TU': true
  'UR': false
  'WR': true
  'WS': false
productavailability:
  '01': false
  '10': true
  '11': true
  '12': false
  '20': true
  '21': true
  '22': true
  '23': false
  '30': false
  '31': false
  '32': false
  '33': true
  '34': true
  '40': false
  '41': false
  '42': false
  '43': false
  '44': false
  '45': false
  '46': false
  '47': false
  '48': false
  '49': false
  '50': false
  '51': false
  '52': false
  '97': true 
  '98': false
  '99': false
publishingstatus:
  '00': true
  '01': false
  '02': true
  '03': false
  '04': true
  '05': false
  '06': false
  '07': false
  '08': false
  '09': true
  '10': false
  '11': false
  '12': false
  '15': false
  '16': false
notificationtype:
  '01': true
  '02': true
  '03': true
  '04': true
  '05': false
  '08': true
  '09': true
  '12': true
  '13': true
  '14': true